version: "3"
services:
# mysql database
    mysql_database:
      image: mysql
      restart: always
      environment :
        MYSQL_ROOT_PASSWORD: 
        MYSQL_DATABASE: wp_db
        MYSQL_USER: 
        MYSQL_PASSWORD: 
      volumes:
          - mysql:/var/lib/mysql 
# wordpress on apache
    wordpress:
      depends_on :
          - mysql_database
      image: wordpress:latest
      restart: always
      ports:
          - "8000:80"
      environment:
          WORDPRESS_DB_HOST: mysql_database:3306
          WORDPRESS_DB_USER: 
          WORDPRESS_DB_PASSWORD: 
          WORDPRESS_DB_NAME: 
      volumes:
          ["./:/var/www/html"]
 # image for phpmyadmin
    phpmyadmin:
      depends_on:
          - mysql_database
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
          - '8080:80'
      environment:
          PMA_HOST: mysql_database
          MYSQL_ROOT_PASSWORD: 1234
volumes:
  mysql: {}
